name: GMoll
main: me.YvesLuca.GMoll.Main
version: 1.0
api-version: 1.15
author: Yves + Luca
depend: [NBTAPI, Essentials, MarriageMaster]

commands:
  head:
    permission: gmoll.head
    description: Buy heads from the head-shop!
  die:
    description: Take a glance at Muffin_TV and commit suicide straight after.
  eat:
    permission: gmoll.eat
    description: You are not yourself, when you're hungry!
  love:
    permission: gmoll.love
    description: Have fun with your friends!
  loveaccept:
    permission: gmoll.loveaccept
    description: Start the fun :)
  smallestb16:
    permission: gmoll.smallestb16
    description: Teleport inside your favorite Admin at any time :)
  MuffinTv:
    permission: gmoll.MuffinTv
    description: Teleport Muffin 3 blocks above his current position
  Goddude:
    permission: gmoll.Goddude
    description: Go to GOD
  cc:
    permission: gmoll.cc
    description: Chatclear
  gsell:
    permission: gmoll.gsell
    description: Sell back the bank ticket
  bank:
    permission: gmoll.bank
    description: Got a bank ticket with a worth
  gamble:
    permission: gmoll.gamble
    description: Winning money by gambling
  genchant:
    permission: gmoll.genchant
    description: Winning money by gambling
  fight:
  