name: GMoll
main: me.YvesLuca.GMoll.Main
version: 1.0
api-version: 1.15
author: Yves + Luca
depend: [NBTAPI, Essentials]

commands:
  head:
    permission: gmoll.head
  die:
  eat:
    permission: gmoll.eat
  love:
    permission: gmoll.love
  smallestb16:
  